spring:
  r2dbc:
    url: r2dbc:postgresql://postgres:5432/userdb
    username: user_user
    password: user_pass
  flyway:
    url: jdbc:postgresql://postgres:5432/userdb
    user: user_user
    password: user_pass

jwt:
  issuer: http://user-service:8089
