spring:
  r2dbc:
    url: r2dbc:postgresql://postgres:5432/inventorydb
    username: inventory_user
    password: inventory_pass

  flyway:
    url: jdbc:postgresql://postgres:5432/inventorydb
    user: inventory_user
    password: inventory_pass

  datasource:
    url: jdbc:postgresql://postgres:5432/inventorydb
    username: inventory_user
    password: inventory_pass

app:
  security:
    enabled: false

logging:
  level:
    org.example.inventory: INFO
