spring:
  r2dbc:
    url: r2dbc:postgresql://postgres:5432/merchandisedb
    username: merchandise_user
    password: merchandise_pass

  flyway:
    url: jdbc:postgresql://postgres:5432/merchandisedb
    user: merchandise_user
    password: merchandise_pass

  datasource:
    url: jdbc:postgresql://postgres:5432/merchandisedb
    username: merchandise_user
    password: merchandise_pass

app:
  security:
    enabled: false

logging:
  level:
    org.example.merchandise: INFO
    org.springframework.r2dbc: WARN
