spring:
  r2dbc:
    url: r2dbc:postgresql://postgres:5432/pricedb
    username: price_user
    password: price_pass

  flyway:
    url: jdbc:postgresql://postgres:5432/pricedb
    user: price_user
    password: price_pass

  datasource:
    url: jdbc:postgresql://postgres:5432/pricedb
    username: price_user
    password: price_pass

app:
  security:
    enabled: false

logging:
  level:
    org.example.price: INFO
